<?php
//Walkers
require_once('walkers/wp_bootstrap_navwalker.php');
require_once('walkers/wp_bootstrap_comment_walker.php');
//General
require_once('helpers.php');
require_once('functions.php');
require_once('shortcodes.php');
require_once('checkupdates.php');
//Widgets
require_once('widgets/search.php');
//TinyMCE
require_once('tinymce/gekoplugins.php');
